apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ade-jsd
spec:
  destination:
    namespace: jira-service-desk
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: ade
      releaseNamespace: jira-service-desk
    path: jira-service-desk
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
