apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ade-jsd
  namespace: argocd
spec:
  destination:
    namespace: jira-service-desk
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: ade-jsd
      releaseNamespace: jira-service-desk
      values: |
        hosts:
          - ade-jsd.core-systems.agiledigital.co
    path: jira-service-desk
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
